name: Use Global Notarize

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write        # ensures push permission is available to the called workflow

jobs:
  call-notarize:
    uses: TheRickyFoster/global-notarization/.github/workflows/notarize.yml@main
    secrets: inherit      # passes caller secrets to the called workflow (if needed)
